spring:
  application:
    name: MyAppointments
    prefix: ap-dev
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: https://az-db-creds.vault.azure.net/
  datasource:
    url: ${DB_CONNECTION_STRING}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: adminuser
    password: Passw0rd
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
app:
  auth:
    user: user
    password: password

#  devtools:
#    restart:
#      enabled: true
#      poll-interval: 2s
#      quiet-period: 1s
#    livereload:
#      enabled: true